### ISSUE TITLE
Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.

### ISSUE THREAD

**Issue by MBing** [brigand/react-pixi-boilerplate#1]
Seems to be having this problem when installing and trying to run.

```
npm install
npm start
```

Solution for me:
[StackOverflow Link](http://stackoverflow.com/questions/37895944/react-transform-catch-errors-does-not-look-like-a-react-component/37950114)

Anyone else has this issue?

**Comment by brigand** [comment]
@MBing thanks for the report; fixed.
